<a href="https://colab.research.google.com/github/JefNtungila/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/LS_DS_Unit_4_Sprint_2_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Perceptron on XOR Gates](#Q2)
3. [Multilayer Perceptron](#Q3)
4. [Keras MMP](#Q4)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:** 
- **Input Layer:** 
- **Hidden Layer:** 
- **Output Layer:**
- **Activation:**
- **Backpropagation:**


### 1 -  A node connecting the information input to the output information can be considered a  neuron
### 2 - The input layer is the layer that gets the data into the hidden layer
### 3 - The hidden layer consists of one or multiple layers of nodes/ neuros
### 4 - The output layer returns the processed result. 
### 5 - Activation helps a model learn. Perceptron are either 0 and 1. Activation adds weights and hence more control.
### 6 - Backpropagation is the process of calculating the gradient of the error.


## 2. Perceptron on XOR Gates <a id="Q2"></a>

The XOr, or “exclusive or”, problem is a classic problem in ANN research. It is the problem of using a neural network to predict the outputs of XOr logic gates given two binary inputs. An XOr function should return a true value if the two inputs are not equal and a false value if they are equal. Create a perceptron class that can model the behavior of an AND gate. You can use the following table as your training data:

|x1	|x2 | y |
|---|---|---|
| 0 | 0 | 0 |
| 0 | 1 | 1 |
| 1 | 1 | 0 |
| 1 | 0 | 1 |


In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

x1 = [0, 0, 1, 1]
x2 = [0, 1, 1, 0]
y = [0 , 1, 0, 1]
predictions = np.add(x1, x2)
difference = np.subtract(predictions, y)
difference_squared = np.square(difference)

df = pd.DataFrame({'x1': x1, 'x2': x2, "y": y, "predictions": predictions, 
                   "difference": difference, "diff_squared": difference_squared})
df.head()

x1  x2  y  predictions  difference  diff_squared
0   0   0  0            0           0             0
1   0   1  1            1           0             0
2   1   1  0            2           2             4
3   1   0  1            1           0             0

## 3. Multilayer Perceptron <a id="Q3"></a>

Implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights.
Your network must have one hidden layer.
You do not have to update weights via gradient descent. You can use something like the derivative of the sigmoid function to update weights.
Train your model on the Heart Disease dataset from UCI:



In [0]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')

In [14]:
df.columns.values

array(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype=object)

In [40]:
from sklearn.model_selection import train_test_split

X = df.drop('target', axis = 1)
y = df['target']
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape) 
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)


(203, 13) (100, 13) (203,) (100,)


###training

In [61]:
 
import numpy as np

class NeuralNetwork():
    
    def __init__(self):
        # seeding for random number generation
        np.random.seed(1)
        
        #converting weights to a 3 by 1 matrix with values from -1 to 1 and mean of 0
        self.synaptic_weights = 2 * np.random.random((13, 203)) - 1

    def sigmoid(self, x):
        #applying the sigmoid function
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        #computing derivative to the Sigmoid function
        return x * (1 - x)

    def train(self, training_inputs, training_outputs, training_iterations):
        
        #training the model to make accurate predictions while adjusting weights continually
        for iteration in range(training_iterations):
            #siphon the training data via  the neuron
            output = self.think(training_inputs)

            #computing error rate for back-propagation
            error = training_outputs - output
            
            #performing weight adjustments
            adjustments = np.dot(training_inputs.T, error * self.sigmoid_derivative(output))

            self.synaptic_weights += adjustments

    def think(self, inputs):
        #passing the inputs via the neuron to get output   
        #converting values to floats
        
        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
        return output


if __name__ == "__main__":

    #initializing the neuron class
    neural_network = NeuralNetwork()

    print("Beginning Randomly Generated Weights: ")
    print(neural_network.synaptic_weights)

    #training data consisting of 4 examples--3 input values and 1 output
    training_inputs = X_train.to_numpy()

    training_outputs = y_train.to_numpy()

    #training taking place
    neural_network.train(training_inputs, training_outputs, 15000)

    print("Ending Weights After Training: ")
    print(neural_network.synaptic_weights)


Beginning Randomly Generated Weights: 
[[-0.16595599  0.44064899 -0.99977125 ...  0.90035224  0.11330638
   0.8312127 ]
 [ 0.28313242 -0.21998457 -0.02801867 ...  0.4187745  -0.06999704
   0.89509788]
 [-0.55713453 -0.46585596 -0.83705207 ...  0.42262904  0.10776922
  -0.39096402]
 ...
 [-0.43013571  0.5377057   0.28156541 ...  0.7405159   0.09393662
   0.0863281 ]
 [ 0.23145186 -0.395637   -0.26653604 ... -0.58380518  0.49099666
  -0.19318674]
 [-0.03105988  0.77491016 -0.7251129  ...  0.89126857 -0.23217152
  -0.62207481]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: overflow encountered in exp
  from ipykernel import kernelapp as app


Ending Weights After Training: 
[[-0.16595599  0.44064899 -0.99977125 ...  0.90035224  0.11330364
   0.8312127 ]
 [ 0.28313242 -0.21998457 -0.02801867 ...  0.4187745  -0.06999704
   0.89509788]
 [-0.55713453 -0.46585596 -0.83705207 ...  0.42262904  0.10776914
  -0.39096402]
 ...
 [-0.43013571  0.5377057   0.28156541 ...  0.7405159   0.09393658
   0.0863281 ]
 [ 0.23145186 -0.395637   -0.26653604 ... -0.58380518  0.49099666
  -0.19318674]
 [-0.03105988  0.77491016 -0.7251129  ...  0.89126857 -0.23217164
  -0.62207481]]


###testing

In [64]:
print(neural_network.think(y[0]))

[[0.45860596 0.60841366 0.2689864  ... 0.71102188 0.52829565 0.69661129]
 [0.57031401 0.44522458 0.49299579 ... 0.60318996 0.48250788 0.70994108]
 [0.36421073 0.38559755 0.30215602 ... 0.60411218 0.52691624 0.40348525]
 ...
 [0.39409393 0.63127854 0.56992996 ... 0.67710866 0.52346689 0.52156863]
 [0.55760603 0.40236105 0.43375769 ... 0.35805749 0.62034119 0.45185296]
 [0.49223565 0.6845821  0.32626808 ... 0.70915189 0.44221642 0.34930971]]


## 4. Keras MMP <a id="Q4"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 5 parameters in order to get a 3 on this section.

###Baseline

In [0]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd
import numpy
# fix random seed for reproducibility
numpy.random.seed(42)

In [33]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)
print(X)

[[ 0.9521966   0.68100522  1.97312292 ... -2.27457861 -0.71442887
  -2.14887271]
 [-1.91531289  0.68100522  1.00257707 ... -2.27457861 -0.71442887
  -0.51292188]
 [-1.47415758 -1.46841752  0.03203122 ...  0.97635214 -0.71442887
  -0.51292188]
 ...
 [ 1.50364073  0.68100522 -0.93851463 ... -0.64911323  1.24459328
   1.12302895]
 [ 0.29046364  0.68100522 -0.93851463 ... -0.64911323  0.26508221
   1.12302895]
 [ 0.29046364 -1.46841752  0.03203122 ... -0.64911323  0.26508221
  -0.51292188]]


In [36]:
# Important Hyperparameters
inputs = X.shape[1]
epochs = 50
batch_size = 10

# Create Model
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(inputs,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(1))
# Compile Model
model.compile(optimizer='adam', loss='mse', metrics=['mse'])
# Fit Model
model.fit(X, y, validation_split=0.33, epochs=epochs, batch_size=batch_size)

W0816 16:45:22.067569 140693847697280 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Train on 203 samples, validate on 100 samples
Epoch 1/50
203/203 [==============================] - 0s 2ms/sample - loss: 0.4645 - mean_squared_error: 0.4645 - val_loss: 0.9036 - val_mean_squared_error: 0.9036
Epoch 2/50
203/203 [==============================] - 0s 215us/sample - loss: 0.1392 - mean_squared_error: 0.1392 - val_loss: 0.3651 - val_mean_squared_error: 0.3651
Epoch 3/50
203/203 [==============================] - 0s 212us/sample - loss: 0.0999 - mean_squared_error: 0.0999 - val_loss: 0.4506 - val_mean_squared_error: 0.4506
Epoch 4/50
203/203 [==============================] - 0s 204us/sample - loss: 0.0827 - mean_squared_error: 0.0827 - val_loss: 0.3978 - val_mean_squared_error: 0.3978
Epoch 5/50
203/203 [==============================] - 0s 222us/sample - loss: 0.0708 - mean_squared_error: 0.0708 - val_loss: 0.4566 - val_mean_squared_error: 0.4566
Epoch 6/50
203/203 [==============================] - 0s 215us/sample - loss: 0.0642 - mean_squared_error: 0.0642 - val_loss: 

### Parameter tuning

In [39]:
import numpy
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

# # fix random seed for reproducibility
# seed = 7
# numpy.random.seed(seed)

# # load dataset
# url ="https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"

# dataset = pd.read_csv(url, header=None).values

# # split into input (X) and output (Y) variables
# X = dataset[:,0:8]
# Y = dataset[:,8]

# Function to create model, required for KerasClassifier
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(12, input_dim=13, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

# define the grid search parameters
# batch_size = [10, 20, 40, 60, 80, 100]
# param_grid = dict(batch_size=batch_size, epochs=epochs)

# define the grid search parameters
param_grid = {'batch_size': [10, 20, 40, 60, 80, 100],
              'epochs': [20]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X, y)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


Best: 0.7161716222763062 using {'batch_size': 60, 'epochs': 20}
Means: 0.6468646923700968, Stdev: 0.11835260513779586 with: {'batch_size': 10, 'epochs': 20}
Means: 0.6534653604030609, Stdev: 0.1146122535976251 with: {'batch_size': 20, 'epochs': 20}
Means: 0.6072607338428497, Stdev: 0.1346275748110329 with: {'batch_size': 40, 'epochs': 20}
Means: 0.7161716222763062, Stdev: 0.09644646179303741 with: {'batch_size': 60, 'epochs': 20}
Means: 0.3960396060720086, Stdev: 0.273788187979495 with: {'batch_size': 80, 'epochs': 20}
Means: 0.48514851927757263, Stdev: 0.17729870427216968 with: {'batch_size': 100, 'epochs': 20}
